name: mytracker_sdk
description: A Flutter plugin for MyTracker SDK. Supports iOS and Android.
version: 3.0.1
author: "My.com"
homepage: "https://tracker.my.com"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=2.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.my.tracker
        pluginClass: MyTrackerSDKPlugin
      ios:
        package: com.my.tracker
        pluginClass: MyTrackerSDKPlugin